version: '3.8'
services:
  backend:
    container_name: 'laravel-admin-backend'
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 8000:8000
      # changes made from app will be push to working dir
    volumes:
      - .:/app
    depends_on:
        - db

  db:
    image: mysql:5.7.22
    container_name: 'mysql'
    environment:
        MYSQL_DATABASE: admin
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33066:3306
