version: '3.8'
services:
  frontend:
    image: henrysweb/admin-frontend
    ports:
      - 8080:80
    depends_on:
        - backendapi

  backendapi:
    container_name: 'backend-api'
    image: henrysweb/backendapi:v1.0
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
        - .env
      # changes made from app will be push to working dir
    volumes:
      - .:/app
    depends_on:
        - db

  db:
    image: mysql:5.7.22
    container_name: 'mysql'
    environment:
        - MYSQL_DATABASE=${DB_DATABASE}
        - MYSQL_USER=${DB_USERNAME}
        - MYSQL_PASSWORD=${DB_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33066:3306
